# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v3_supplies_supply_id_trbx_post_request import ApiV3SuppliesSupplyIdTrbxPostRequest

class TestApiV3SuppliesSupplyIdTrbxPostRequest(unittest.TestCase):
    """ApiV3SuppliesSupplyIdTrbxPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3SuppliesSupplyIdTrbxPostRequest:
        """Test ApiV3SuppliesSupplyIdTrbxPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3SuppliesSupplyIdTrbxPostRequest`
        """
        model = ApiV3SuppliesSupplyIdTrbxPostRequest()
        if include_optional:
            return ApiV3SuppliesSupplyIdTrbxPostRequest(
                amount = 4
            )
        else:
            return ApiV3SuppliesSupplyIdTrbxPostRequest(
                amount = 4,
        )
        """

    def testApiV3SuppliesSupplyIdTrbxPostRequest(self):
        """Test ApiV3SuppliesSupplyIdTrbxPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
