# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.commission_china import CommissionChina

class TestCommissionChina(unittest.TestCase):
    """CommissionChina unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommissionChina:
        """Test CommissionChina
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommissionChina`
        """
        model = CommissionChina()
        if include_optional:
            return CommissionChina(
                report = [
                    wildberries_async_api_client.models.commission_china_report_inner.CommissionChina_report_inner(
                        kgvp_china = 1.337, 
                        parent_id = 56, 
                        parent_name = '', 
                        subject_id = 56, 
                        subject_name = '', )
                    ]
            )
        else:
            return CommissionChina(
        )
        """

    def testCommissionChina(self):
        """Test CommissionChina"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
