# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.request_with_date_inner import RequestWithDateInner

class TestRequestWithDateInner(unittest.TestCase):
    """RequestWithDateInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestWithDateInner:
        """Test RequestWithDateInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestWithDateInner`
        """
        model = RequestWithDateInner()
        if include_optional:
            return RequestWithDateInner(
                id = 56,
                dates = [
                    datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
                    ]
            )
        else:
            return RequestWithDateInner(
        )
        """

    def testRequestWithDateInner(self):
        """Test RequestWithDateInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
