# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v1_feedback_get200_response_data_photo_links_inner import ApiV1FeedbackGet200ResponseDataPhotoLinksInner

class TestApiV1FeedbackGet200ResponseDataPhotoLinksInner(unittest.TestCase):
    """ApiV1FeedbackGet200ResponseDataPhotoLinksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1FeedbackGet200ResponseDataPhotoLinksInner:
        """Test ApiV1FeedbackGet200ResponseDataPhotoLinksInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1FeedbackGet200ResponseDataPhotoLinksInner`
        """
        model = ApiV1FeedbackGet200ResponseDataPhotoLinksInner()
        if include_optional:
            return ApiV1FeedbackGet200ResponseDataPhotoLinksInner(
                full_size = '',
                mini_size = ''
            )
        else:
            return ApiV1FeedbackGet200ResponseDataPhotoLinksInner(
        )
        """

    def testApiV1FeedbackGet200ResponseDataPhotoLinksInner(self):
        """Test ApiV1FeedbackGet200ResponseDataPhotoLinksInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
