# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_tags_get200_response import ContentV2TagsGet200Response

class TestContentV2TagsGet200Response(unittest.TestCase):
    """ContentV2TagsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2TagsGet200Response:
        """Test ContentV2TagsGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2TagsGet200Response`
        """
        model = ContentV2TagsGet200Response()
        if include_optional:
            return ContentV2TagsGet200Response(
                data = wildberries_async_api_client.models._content_v2_tags_get_200_response_data._content_v2_tags_get_200_response_data(
                    id = 56, 
                    color = '', 
                    name = '', ),
                error = False,
                error_text = '',
                additional_errors = ''
            )
        else:
            return ContentV2TagsGet200Response(
        )
        """

    def testContentV2TagsGet200Response(self):
        """Test ContentV2TagsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
