# coding: utf-8

"""
    Описание API Marketplace

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wb_client.models.api_v3_orders_status_post200_response_orders_inner import ApiV3OrdersStatusPost200ResponseOrdersInner

class TestApiV3OrdersStatusPost200ResponseOrdersInner(unittest.TestCase):
    """ApiV3OrdersStatusPost200ResponseOrdersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3OrdersStatusPost200ResponseOrdersInner:
        """Test ApiV3OrdersStatusPost200ResponseOrdersInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3OrdersStatusPost200ResponseOrdersInner`
        """
        model = ApiV3OrdersStatusPost200ResponseOrdersInner()
        if include_optional:
            return ApiV3OrdersStatusPost200ResponseOrdersInner(
                id = 5632423,
                supplier_status = 'new',
                wb_status = 'waiting'
            )
        else:
            return ApiV3OrdersStatusPost200ResponseOrdersInner(
        )
        """

    def testApiV3OrdersStatusPost200ResponseOrdersInner(self):
        """Test ApiV3OrdersStatusPost200ResponseOrdersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
