# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v1_auto_updatenm_post_request import AdvV1AutoUpdatenmPostRequest

class TestAdvV1AutoUpdatenmPostRequest(unittest.TestCase):
    """AdvV1AutoUpdatenmPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV1AutoUpdatenmPostRequest:
        """Test AdvV1AutoUpdatenmPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV1AutoUpdatenmPostRequest`
        """
        model = AdvV1AutoUpdatenmPostRequest()
        if include_optional:
            return AdvV1AutoUpdatenmPostRequest(
                add = [
                    56
                    ],
                delete = [
                    56
                    ]
            )
        else:
            return AdvV1AutoUpdatenmPostRequest(
        )
        """

    def testAdvV1AutoUpdatenmPostRequest(self):
        """Test AdvV1AutoUpdatenmPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
