# coding: utf-8

"""
    Описание API Marketplace

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wb_client.models.order_new import OrderNew

class TestOrderNew(unittest.TestCase):
    """OrderNew unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderNew:
        """Test OrderNew
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderNew`
        """
        model = OrderNew()
        if include_optional:
            return OrderNew(
                id = 13833711,
                rid = 'f884001e44e511edb8780242ac120002',
                created_at = '2022-05-04T07:56:29Z',
                warehouse_id = 658434,
                offices = [
                    'Калуга'
                    ],
                address = wb_client.models.order_address.Order_address(
                    full_address = 'Челябинская область, г. Челябинск, 51-я улица Арабкира, д. 10А, кв. 42', 
                    province = 'Челябинская область', 
                    area = 'Челябинск', 
                    city = 'Город', 
                    street = '51-я улица Арабкира', 
                    home = '10А', 
                    flat = '42', 
                    entrance = '3', 
                    longitude = 44.519068, 
                    latitude = 40.20192, ),
                required_meta = ["uin"],
                user = wb_client.models.order_user.Order_user(
                    fio = '', 
                    phone = '', ),
                skus = [
                    '6665956397512'
                    ],
                price = 56,
                converted_price = 56,
                currency_code = 56,
                converted_currency_code = 56,
                order_uid = '',
                delivery_type = 'dbs',
                nm_id = 56,
                chrt_id = 56,
                article = 'one-ring-7548',
                color_code = 'RAL 3017',
                cargo_type = 1
            )
        else:
            return OrderNew(
        )
        """

    def testOrderNew(self):
        """Test OrderNew"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
