# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v1_analytics_acceptance_report_get200_response import ApiV1AnalyticsAcceptanceReportGet200Response

class TestApiV1AnalyticsAcceptanceReportGet200Response(unittest.TestCase):
    """ApiV1AnalyticsAcceptanceReportGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1AnalyticsAcceptanceReportGet200Response:
        """Test ApiV1AnalyticsAcceptanceReportGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1AnalyticsAcceptanceReportGet200Response`
        """
        model = ApiV1AnalyticsAcceptanceReportGet200Response()
        if include_optional:
            return ApiV1AnalyticsAcceptanceReportGet200Response(
                report = [
                    wildberries_async_api_client.models._api_v1_analytics_acceptance_report_get_200_response_report_inner._api_v1_analytics_acceptance_report_get_200_response_report_inner(
                        count = 40, 
                        gi_create_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        income_id = 11834106, 
                        nm_id = 123456789, 
                        shkсreate_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        subject_name = 'Добавки пищевые', 
                        sum = 200, 
                        total = 200.5, )
                    ]
            )
        else:
            return ApiV1AnalyticsAcceptanceReportGet200Response(
        )
        """

    def testApiV1AnalyticsAcceptanceReportGet200Response(self):
        """Test ApiV1AnalyticsAcceptanceReportGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
