# coding: utf-8

"""
    Описание API Marketplace

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wb_client.models.api_v3_passes_post_request import ApiV3PassesPostRequest

class TestApiV3PassesPostRequest(unittest.TestCase):
    """ApiV3PassesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3PassesPostRequest:
        """Test ApiV3PassesPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3PassesPostRequest`
        """
        model = ApiV3PassesPostRequest()
        if include_optional:
            return ApiV3PassesPostRequest(
                first_name = 'Александр',
                last_name = 'Петров',
                car_model = 'Lamborghini',
                car_number = 'A456BC123',
                office_id = 15
            )
        else:
            return ApiV3PassesPostRequest(
                first_name = 'Александр',
                last_name = 'Петров',
                car_model = 'Lamborghini',
                car_number = 'A456BC123',
                office_id = 15,
        )
        """

    def testApiV3PassesPostRequest(self):
        """Test ApiV3PassesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
