# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.supply import Supply

class TestSupply(unittest.TestCase):
    """Supply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Supply:
        """Test Supply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Supply`
        """
        model = Supply()
        if include_optional:
            return Supply(
                id = 'WB-GI-1234567',
                done = True,
                created_at = '2022-05-04T07:56:29Z',
                closed_at = '2022-05-04T07:56:29Z',
                scan_dt = '2022-05-04T07:56:29Z',
                name = 'Тестовая поставка',
                cargo_type = 0
            )
        else:
            return Supply(
        )
        """

    def testSupply(self):
        """Test Supply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
