# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v3_orders_order_id_meta_get200_response import ApiV3OrdersOrderIdMetaGet200Response

class TestApiV3OrdersOrderIdMetaGet200Response(unittest.TestCase):
    """ApiV3OrdersOrderIdMetaGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3OrdersOrderIdMetaGet200Response:
        """Test ApiV3OrdersOrderIdMetaGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3OrdersOrderIdMetaGet200Response`
        """
        model = ApiV3OrdersOrderIdMetaGet200Response()
        if include_optional:
            return ApiV3OrdersOrderIdMetaGet200Response(
                meta = wildberries_async_api_client.models.meta.Meta(
                    imei = '123456789012345', 
                    uin = '1234567890123456', 
                    gtin = '1234567890123', 
                    sgtin = '1234567890123456', )
            )
        else:
            return ApiV3OrdersOrderIdMetaGet200Response(
        )
        """

    def testApiV3OrdersOrderIdMetaGet200Response(self):
        """Test ApiV3OrdersOrderIdMetaGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
