# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.response_info_advert import ResponseInfoAdvert

class TestResponseInfoAdvert(unittest.TestCase):
    """ResponseInfoAdvert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseInfoAdvert:
        """Test ResponseInfoAdvert
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseInfoAdvert`
        """
        model = ResponseInfoAdvert()
        if include_optional:
            return ResponseInfoAdvert(
                advert_id = 1234,
                type = 4,
                status = 9,
                daily_budget = 56,
                create_time = '2022-03-09T10:50:21.831623+03:00',
                change_time = '2022-12-22T18:24:19.808701+03:00',
                start_time = '',
                end_time = '',
                name = '',
                params = [
                    wildberries_async_api_client.models.response_info_advert_params_inner.ResponseInfoAdvert_params_inner(
                        subject_name = '', 
                        active = True, 
                        intervals = [
                            wildberries_async_api_client.models.response_info_advert_params_inner_intervals_inner.ResponseInfoAdvert_params_inner_intervals_inner(
                                begin = 56, 
                                end = 56, )
                            ], 
                        price = 56, 
                        menu_id = 56, 
                        subject_id = 56, 
                        set_id = 56, 
                        set_name = '', 
                        menu_name = '', 
                        nms = [
                            wildberries_async_api_client.models.response_info_advert_params_inner_nms_inner.ResponseInfoAdvert_params_inner_nms_inner(
                                nm = 56, 
                                active = True, )
                            ], )
                    ],
                search_pluse_state = True
            )
        else:
            return ResponseInfoAdvert(
        )
        """

    def testResponseInfoAdvert(self):
        """Test ResponseInfoAdvert"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
