# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.sales_item import SalesItem

class TestSalesItem(unittest.TestCase):
    """SalesItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SalesItem:
        """Test SalesItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SalesItem`
        """
        model = SalesItem()
        if include_optional:
            return SalesItem(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_change_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                warehouse_name = '',
                country_name = '',
                oblast_okrug_name = '',
                region_name = '',
                supplier_article = '',
                nm_id = 56,
                barcode = '',
                category = '',
                subject = '',
                brand = '',
                tech_size = '',
                income_id = 56,
                is_supply = True,
                is_realization = True,
                total_price = 1.337,
                discount_percent = 56,
                spp = 1.337,
                payment_sale_amount = 56,
                for_pay = 1.337,
                finished_price = 1.337,
                price_with_disc = 1.337,
                sale_id = '',
                order_type = '',
                sticker = '',
                g_number = '',
                srid = ''
            )
        else:
            return SalesItem(
        )
        """

    def testSalesItem(self):
        """Test SalesItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
