# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.request_with_interval_inner import RequestWithIntervalInner

class TestRequestWithIntervalInner(unittest.TestCase):
    """RequestWithIntervalInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestWithIntervalInner:
        """Test RequestWithIntervalInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestWithIntervalInner`
        """
        model = RequestWithIntervalInner()
        if include_optional:
            return RequestWithIntervalInner(
                id = 56,
                interval = wildberries_async_api_client.models.request_with_interval_inner_interval.RequestWithInterval_inner_interval(
                    begin = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
            )
        else:
            return RequestWithIntervalInner(
        )
        """

    def testRequestWithIntervalInner(self):
        """Test RequestWithIntervalInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
