# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v2_nm_report_downloads_file_download_id_get429_response import ApiV2NmReportDownloadsFileDownloadIdGet429Response

class TestApiV2NmReportDownloadsFileDownloadIdGet429Response(unittest.TestCase):
    """ApiV2NmReportDownloadsFileDownloadIdGet429Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV2NmReportDownloadsFileDownloadIdGet429Response:
        """Test ApiV2NmReportDownloadsFileDownloadIdGet429Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV2NmReportDownloadsFileDownloadIdGet429Response`
        """
        model = ApiV2NmReportDownloadsFileDownloadIdGet429Response()
        if include_optional:
            return ApiV2NmReportDownloadsFileDownloadIdGet429Response(
                code = 429,
                message = 'Текст ошибки',
                data = [
                    None
                    ],
                error = True,
                error_text = 'Превышен лимит отчётов в сутки. Максимальное количество отчётов - 20',
                additional_errors = [
                    wildberries_async_api_client.models.response_error_additional_errors_inner.responseError_additionalErrors_inner(
                        field = '', 
                        description = '', )
                    ]
            )
        else:
            return ApiV2NmReportDownloadsFileDownloadIdGet429Response(
        )
        """

    def testApiV2NmReportDownloadsFileDownloadIdGet429Response(self):
        """Test ApiV2NmReportDownloadsFileDownloadIdGet429Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
