# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_object_charcs_subject_id_get200_response_data_inner import ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner

class TestContentV2ObjectCharcsSubjectIdGet200ResponseDataInner(unittest.TestCase):
    """ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner:
        """Test ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner`
        """
        model = ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner()
        if include_optional:
            return ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner(
                charc_id = 56,
                subject_name = '',
                subject_id = 56,
                name = '',
                required = True,
                unit_name = '',
                max_count = 56,
                popular = True,
                charc_type = 56
            )
        else:
            return ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner(
        )
        """

    def testContentV2ObjectCharcsSubjectIdGet200ResponseDataInner(self):
        """Test ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
