# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v1_search_supplier_products_get200_response_inner_subject import AdvV1SearchSupplierProductsGet200ResponseInnerSubject

class TestAdvV1SearchSupplierProductsGet200ResponseInnerSubject(unittest.TestCase):
    """AdvV1SearchSupplierProductsGet200ResponseInnerSubject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV1SearchSupplierProductsGet200ResponseInnerSubject:
        """Test AdvV1SearchSupplierProductsGet200ResponseInnerSubject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV1SearchSupplierProductsGet200ResponseInnerSubject`
        """
        model = AdvV1SearchSupplierProductsGet200ResponseInnerSubject()
        if include_optional:
            return AdvV1SearchSupplierProductsGet200ResponseInnerSubject(
                id = 56,
                name = ''
            )
        else:
            return AdvV1SearchSupplierProductsGet200ResponseInnerSubject(
        )
        """

    def testAdvV1SearchSupplierProductsGet200ResponseInnerSubject(self):
        """Test AdvV1SearchSupplierProductsGet200ResponseInnerSubject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
