# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_cards_upload_add_post_request_cards_to_add_inner_characteristics_inner import ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner

class TestContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner(unittest.TestCase):
    """ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner:
        """Test ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner`
        """
        model = ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner()
        if include_optional:
            return ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner(
                id = 56,
                value = None
            )
        else:
            return ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner(
        )
        """

    def testContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner(self):
        """Test ContentV2CardsUploadAddPostRequestCardsToAddInnerCharacteristicsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
