# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_cards_update_post_request_inner_dimensions import ContentV2CardsUpdatePostRequestInnerDimensions

class TestContentV2CardsUpdatePostRequestInnerDimensions(unittest.TestCase):
    """ContentV2CardsUpdatePostRequestInnerDimensions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2CardsUpdatePostRequestInnerDimensions:
        """Test ContentV2CardsUpdatePostRequestInnerDimensions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2CardsUpdatePostRequestInnerDimensions`
        """
        model = ContentV2CardsUpdatePostRequestInnerDimensions()
        if include_optional:
            return ContentV2CardsUpdatePostRequestInnerDimensions(
                length = 56,
                width = 56,
                height = 56
            )
        else:
            return ContentV2CardsUpdatePostRequestInnerDimensions(
        )
        """

    def testContentV2CardsUpdatePostRequestInnerDimensions(self):
        """Test ContentV2CardsUpdatePostRequestInnerDimensions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
