# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v3_orders_order_id_meta_imei_put_request import ApiV3OrdersOrderIdMetaImeiPutRequest

class TestApiV3OrdersOrderIdMetaImeiPutRequest(unittest.TestCase):
    """ApiV3OrdersOrderIdMetaImeiPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3OrdersOrderIdMetaImeiPutRequest:
        """Test ApiV3OrdersOrderIdMetaImeiPutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3OrdersOrderIdMetaImeiPutRequest`
        """
        model = ApiV3OrdersOrderIdMetaImeiPutRequest()
        if include_optional:
            return ApiV3OrdersOrderIdMetaImeiPutRequest(
                imei = '123456789012345'
            )
        else:
            return ApiV3OrdersOrderIdMetaImeiPutRequest(
                imei = '123456789012345',
        )
        """

    def testApiV3OrdersOrderIdMetaImeiPutRequest(self):
        """Test ApiV3OrdersOrderIdMetaImeiPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
