# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v2_history_goods_task_get200_response_data import ApiV2HistoryGoodsTaskGet200ResponseData

class TestApiV2HistoryGoodsTaskGet200ResponseData(unittest.TestCase):
    """ApiV2HistoryGoodsTaskGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV2HistoryGoodsTaskGet200ResponseData:
        """Test ApiV2HistoryGoodsTaskGet200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV2HistoryGoodsTaskGet200ResponseData`
        """
        model = ApiV2HistoryGoodsTaskGet200ResponseData()
        if include_optional:
            return ApiV2HistoryGoodsTaskGet200ResponseData(
                upload_id = 3235236546,
                history_goods = [
                    wildberries_async_api_client.models.good_history.GoodHistory(
                        nm_id = 544833232, 
                        vendor_code = '34552332', 
                        size_id = 54483342, 
                        tech_size_name = '42', 
                        price = 1500, 
                        currency_iso_code4217 = 'RUB', 
                        discount = 25, 
                        status = 1, 
                        error_text = 'The product is in quarantine', )
                    ]
            )
        else:
            return ApiV2HistoryGoodsTaskGet200ResponseData(
        )
        """

    def testApiV2HistoryGoodsTaskGet200ResponseData(self):
        """Test ApiV2HistoryGoodsTaskGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
