# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_cards_update_post_request_inner_characteristics_inner import ContentV2CardsUpdatePostRequestInnerCharacteristicsInner

class TestContentV2CardsUpdatePostRequestInnerCharacteristicsInner(unittest.TestCase):
    """ContentV2CardsUpdatePostRequestInnerCharacteristicsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2CardsUpdatePostRequestInnerCharacteristicsInner:
        """Test ContentV2CardsUpdatePostRequestInnerCharacteristicsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2CardsUpdatePostRequestInnerCharacteristicsInner`
        """
        model = ContentV2CardsUpdatePostRequestInnerCharacteristicsInner()
        if include_optional:
            return ContentV2CardsUpdatePostRequestInnerCharacteristicsInner(
                id = 56,
                value = None
            )
        else:
            return ContentV2CardsUpdatePostRequestInnerCharacteristicsInner(
        )
        """

    def testContentV2CardsUpdatePostRequestInnerCharacteristicsInner(self):
        """Test ContentV2CardsUpdatePostRequestInnerCharacteristicsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
