# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_get_cards_trash_post200_response_cards_inner_sizes_inner import ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner

class TestContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner(unittest.TestCase):
    """ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner:
        """Test ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner`
        """
        model = ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner()
        if include_optional:
            return ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner(
                chrt_id = 56,
                tech_size = '',
                wb_size = '',
                skus = [
                    '12345Ejf5'
                    ]
            )
        else:
            return ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner(
        )
        """

    def testContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner(self):
        """Test ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
