# coding: utf-8

"""
    Описание API Marketplace

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wb_client.models.api_v3_stocks_warehouse_id_post_request import ApiV3StocksWarehouseIdPostRequest

class TestApiV3StocksWarehouseIdPostRequest(unittest.TestCase):
    """ApiV3StocksWarehouseIdPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3StocksWarehouseIdPostRequest:
        """Test ApiV3StocksWarehouseIdPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3StocksWarehouseIdPostRequest`
        """
        model = ApiV3StocksWarehouseIdPostRequest()
        if include_optional:
            return ApiV3StocksWarehouseIdPostRequest(
                skus = [
                    'BarcodeTest123'
                    ]
            )
        else:
            return ApiV3StocksWarehouseIdPostRequest(
        )
        """

    def testApiV3StocksWarehouseIdPostRequest(self):
        """Test ApiV3StocksWarehouseIdPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
