# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.sender import Sender

class TestSender(unittest.TestCase):
    """Sender unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSender(self):
        """Test Sender"""
        # inst = Sender()

if __name__ == '__main__':
    unittest.main()
