# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.refund import Refund

class TestRefund(unittest.TestCase):
    """Refund unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Refund:
        """Test Refund
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Refund`
        """
        model = Refund()
        if include_optional:
            return Refund(
                action_type = 'sellerRequestRefund',
                price = 56,
                price_currency = '',
                rid = ''
            )
        else:
            return Refund(
        )
        """

    def testRefund(self):
        """Test Refund"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
