# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v1_save_ad_post400_response import AdvV1SaveAdPost400Response

class TestAdvV1SaveAdPost400Response(unittest.TestCase):
    """AdvV1SaveAdPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV1SaveAdPost400Response:
        """Test AdvV1SaveAdPost400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV1SaveAdPost400Response`
        """
        model = AdvV1SaveAdPost400Response()
        if include_optional:
            return AdvV1SaveAdPost400Response(
                error = ''
            )
        else:
            return AdvV1SaveAdPost400Response(
        )
        """

    def testAdvV1SaveAdPost400Response(self):
        """Test AdvV1SaveAdPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
