# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_directory_vat_get200_response import ContentV2DirectoryVatGet200Response

class TestContentV2DirectoryVatGet200Response(unittest.TestCase):
    """ContentV2DirectoryVatGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2DirectoryVatGet200Response:
        """Test ContentV2DirectoryVatGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2DirectoryVatGet200Response`
        """
        model = ContentV2DirectoryVatGet200Response()
        if include_optional:
            return ContentV2DirectoryVatGet200Response(
                data = [
                    ''
                    ],
                error = True,
                error_text = '',
                additional_errors = ''
            )
        else:
            return ContentV2DirectoryVatGet200Response(
        )
        """

    def testContentV2DirectoryVatGet200Response(self):
        """Test ContentV2DirectoryVatGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
