# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_adv_v0_allcpm_post(self) -> None:
        """Test case for adv_v0_allcpm_post

        Список ставок по типу размещения кампании
        """
        pass

    def test_adv_v0_cpm_get(self) -> None:
        """Test case for adv_v0_cpm_get

        Список ставок
        """
        pass

    def test_adv_v0_cpm_post(self) -> None:
        """Test case for adv_v0_cpm_post

        Изменение ставки у кампании
        """
        pass

    def test_adv_v0_delete_get(self) -> None:
        """Test case for adv_v0_delete_get

        Удаление кампании
        """
        pass

    def test_adv_v0_params_menu_get(self) -> None:
        """Test case for adv_v0_params_menu_get

        Словарь значений параметра menuId
        """
        pass

    def test_adv_v0_params_set_get(self) -> None:
        """Test case for adv_v0_params_set_get

        Словарь значений параметра setId
        """
        pass

    def test_adv_v0_params_subject_get(self) -> None:
        """Test case for adv_v0_params_subject_get

        Словарь значений параметра subjectId
        """
        pass

    def test_adv_v1_advert_get(self) -> None:
        """Test case for adv_v1_advert_get

        Информация о медиакампании
        """
        pass

    def test_adv_v1_adverts_get(self) -> None:
        """Test case for adv_v1_adverts_get

        Список медиакампаний
        """
        pass

    def test_adv_v1_auto_stat_get(self) -> None:
        """Test case for adv_v1_auto_stat_get

        Статистика автоматической кампании
        """
        pass

    def test_adv_v1_balance_get(self) -> None:
        """Test case for adv_v1_balance_get

        Баланс
        """
        pass

    def test_adv_v1_budget_deposit_post(self) -> None:
        """Test case for adv_v1_budget_deposit_post

        Пополнение бюджета кампании
        """
        pass

    def test_adv_v1_budget_get(self) -> None:
        """Test case for adv_v1_budget_get

        Бюджет кампании
        """
        pass

    def test_adv_v1_count_get(self) -> None:
        """Test case for adv_v1_count_get

        Получение медиакампаний
        """
        pass

    def test_adv_v1_payments_get(self) -> None:
        """Test case for adv_v1_payments_get

        Получение истории пополнений счета
        """
        pass

    def test_adv_v1_promotion_adverts_post(self) -> None:
        """Test case for adv_v1_promotion_adverts_post

        Информация о кампаниях
        """
        pass

    def test_adv_v1_promotion_count_get(self) -> None:
        """Test case for adv_v1_promotion_count_get

        Списки кампаний
        """
        pass

    def test_adv_v1_save_ad_post(self) -> None:
        """Test case for adv_v1_save_ad_post

        Создать автоматическую кампанию
        """
        pass

    def test_adv_v1_seacat_stat_get(self) -> None:
        """Test case for adv_v1_seacat_stat_get

        Статистика кампаний Поиск + Каталог
        """
        pass

    def test_adv_v1_stat_words_get(self) -> None:
        """Test case for adv_v1_stat_words_get

        Статистика поисковой кампании по ключевым фразам
        """
        pass

    def test_adv_v1_supplier_subjects_get(self) -> None:
        """Test case for adv_v1_supplier_subjects_get

        Предметы для кампаний
        """
        pass

    def test_adv_v1_upd_get(self) -> None:
        """Test case for adv_v1_upd_get

        Получение истории затрат
        """
        pass

    def test_adv_v1_upd_intervals_get(self) -> None:
        """Test case for adv_v1_upd_intervals_get

        Получение месячных интервалов для истории затрат
        """
        pass

    def test_adv_v2_auto_daily_words_get(self) -> None:
        """Test case for adv_v2_auto_daily_words_get

        Детальная статистика автоматической кампании по ключевым фразам
        """
        pass

    def test_adv_v2_auto_stat_words_get(self) -> None:
        """Test case for adv_v2_auto_stat_words_get

        Статистика автоматической кампании по кластерам фраз
        """
        pass

    def test_adv_v2_fullstats_post(self) -> None:
        """Test case for adv_v2_fullstats_post

        Статистика кампаний
        """
        pass

    def test_adv_v2_seacat_save_ad_post(self) -> None:
        """Test case for adv_v2_seacat_save_ad_post

        Создать кампанию Поиск + Каталог
        """
        pass

    def test_adv_v2_supplier_nms_post(self) -> None:
        """Test case for adv_v2_supplier_nms_post

        Номенклатуры для кампаний
        """
        pass

    def test_api_v1_del_post(self) -> None:
        """Test case for api_v1_del_post

        Удаление рекомендаций
        """
        pass

    def test_api_v1_feedback_get(self) -> None:
        """Test case for api_v1_feedback_get

        Получить отзыв по Id
        """
        pass

    def test_api_v1_feedbacks_archive_get(self) -> None:
        """Test case for api_v1_feedbacks_archive_get

        Список архивных отзывов
        """
        pass

    def test_api_v1_feedbacks_count_get(self) -> None:
        """Test case for api_v1_feedbacks_count_get

        Количество отзывов
        """
        pass

    def test_api_v1_feedbacks_count_unanswered_get(self) -> None:
        """Test case for api_v1_feedbacks_count_unanswered_get

        Необработанные отзывы
        """
        pass

    def test_api_v1_feedbacks_get(self) -> None:
        """Test case for api_v1_feedbacks_get

        Список отзывов
        """
        pass

    def test_api_v1_feedbacks_order_return_post(self) -> None:
        """Test case for api_v1_feedbacks_order_return_post

        Возврат товара по ID отзыва
        """
        pass

    def test_api_v1_feedbacks_patch(self) -> None:
        """Test case for api_v1_feedbacks_patch

        Работа с отзывом
        """
        pass

    def test_api_v1_feedbacks_products_rating_get(self) -> None:
        """Test case for api_v1_feedbacks_products_rating_get

        Средняя оценка товаров по родительской категории
        """
        pass

    def test_api_v1_feedbacks_products_rating_nmid_get(self) -> None:
        """Test case for api_v1_feedbacks_products_rating_nmid_get

        Средняя оценка товара по артикулу WB
        """
        pass

    def test_api_v1_feedbacks_products_rating_top_get(self) -> None:
        """Test case for api_v1_feedbacks_products_rating_top_get

        Товары с наибольшей и наименьшей средней оценкой по родительской категории
        """
        pass

    def test_api_v1_feedbacks_report_get(self) -> None:
        """Test case for api_v1_feedbacks_report_get

        Получение отзывов в формате XLSX
        """
        pass

    def test_api_v1_ins_post(self) -> None:
        """Test case for api_v1_ins_post

        Добавление рекомендаций
        """
        pass

    def test_api_v1_list_post(self) -> None:
        """Test case for api_v1_list_post

        Список рекомендаций
        """
        pass

    def test_api_v1_new_feedbacks_questions_get(self) -> None:
        """Test case for api_v1_new_feedbacks_questions_get

        Непросмотренные отзывы и вопросы
        """
        pass

    def test_api_v1_parent_subjects_get(self) -> None:
        """Test case for api_v1_parent_subjects_get

        Родительские категории товаров
        """
        pass

    def test_api_v1_question_get(self) -> None:
        """Test case for api_v1_question_get

        Получить вопрос по Id
        """
        pass

    def test_api_v1_questions_count_get(self) -> None:
        """Test case for api_v1_questions_count_get

        Количество вопросов
        """
        pass

    def test_api_v1_questions_count_unanswered_get(self) -> None:
        """Test case for api_v1_questions_count_unanswered_get

        Неотвеченные вопросы
        """
        pass

    def test_api_v1_questions_get(self) -> None:
        """Test case for api_v1_questions_get

        Список вопросов
        """
        pass

    def test_api_v1_questions_patch(self) -> None:
        """Test case for api_v1_questions_patch

        Работа с вопросами
        """
        pass

    def test_api_v1_questions_products_rating_get(self) -> None:
        """Test case for api_v1_questions_products_rating_get

        Часто спрашиваемые товары
        """
        pass

    def test_api_v1_questions_report_get(self) -> None:
        """Test case for api_v1_questions_report_get

        Получение вопросов в формате XLSX
        """
        pass

    def test_api_v1_set_post(self) -> None:
        """Test case for api_v1_set_post

        Управление рекомендациями
        """
        pass

    def test_api_v1_supplier_incomes_get(self) -> None:
        """Test case for api_v1_supplier_incomes_get

        Поставки
        """
        pass

    def test_api_v1_supplier_orders_get(self) -> None:
        """Test case for api_v1_supplier_orders_get

        Заказы
        """
        pass

    def test_api_v1_supplier_sales_get(self) -> None:
        """Test case for api_v1_supplier_sales_get

        Продажи
        """
        pass

    def test_api_v1_supplier_stocks_get(self) -> None:
        """Test case for api_v1_supplier_stocks_get

        Склад
        """
        pass

    def test_api_v1_supplier_valuations_get(self) -> None:
        """Test case for api_v1_supplier_valuations_get

        Получить список оценок
        """
        pass

    def test_api_v1_tariffs_commission_get(self) -> None:
        """Test case for api_v1_tariffs_commission_get

        Комиссия по категориям товаров
        """
        pass

    def test_api_v3_offices_get(self) -> None:
        """Test case for api_v3_offices_get

        Получить список складов WB
        """
        pass

    def test_api_v3_passes_get(self) -> None:
        """Test case for api_v3_passes_get

        Получить список пропусков
        """
        pass

    def test_api_v3_passes_offices_get(self) -> None:
        """Test case for api_v3_passes_offices_get

        Получить список складов, для которых требуется пропуск
        """
        pass

    def test_api_v3_passes_pass_id_delete(self) -> None:
        """Test case for api_v3_passes_pass_id_delete

        Удалить пропуск
        """
        pass

    def test_api_v3_passes_pass_id_put(self) -> None:
        """Test case for api_v3_passes_pass_id_put

        Обновить пропуск
        """
        pass

    def test_api_v3_passes_post(self) -> None:
        """Test case for api_v3_passes_post

        Создать пропуск
        """
        pass

    def test_api_v3_stocks_warehouse_id_delete(self) -> None:
        """Test case for api_v3_stocks_warehouse_id_delete

        Удалить остатки товаров
        """
        pass

    def test_api_v3_stocks_warehouse_id_post(self) -> None:
        """Test case for api_v3_stocks_warehouse_id_post

        Получить остатки товаров
        """
        pass

    def test_api_v3_stocks_warehouse_id_put(self) -> None:
        """Test case for api_v3_stocks_warehouse_id_put

        Обновить остатки товаров
        """
        pass

    def test_api_v3_supplies_get(self) -> None:
        """Test case for api_v3_supplies_get

        Получить список поставок
        """
        pass

    def test_api_v3_supplies_post(self) -> None:
        """Test case for api_v3_supplies_post

        Создать новую поставку
        """
        pass

    def test_api_v3_supplies_supply_id_barcode_get(self) -> None:
        """Test case for api_v3_supplies_supply_id_barcode_get

        Получить QR поставки
        """
        pass

    def test_api_v3_supplies_supply_id_delete(self) -> None:
        """Test case for api_v3_supplies_supply_id_delete

        Удалить поставку
        """
        pass

    def test_api_v3_supplies_supply_id_deliver_patch(self) -> None:
        """Test case for api_v3_supplies_supply_id_deliver_patch

        Передать поставку в доставку
        """
        pass

    def test_api_v3_supplies_supply_id_get(self) -> None:
        """Test case for api_v3_supplies_supply_id_get

        Получить информацию о поставке
        """
        pass

    def test_api_v3_supplies_supply_id_orders_get(self) -> None:
        """Test case for api_v3_supplies_supply_id_orders_get

        Получить сборочные задания в поставке
        """
        pass

    def test_api_v3_supplies_supply_id_orders_order_id_patch(self) -> None:
        """Test case for api_v3_supplies_supply_id_orders_order_id_patch

        Добавить к поставке сборочное задание
        """
        pass

    def test_api_v3_supplies_supply_id_trbx_delete(self) -> None:
        """Test case for api_v3_supplies_supply_id_trbx_delete

        Удалить короба из поставки
        """
        pass

    def test_api_v3_supplies_supply_id_trbx_get(self) -> None:
        """Test case for api_v3_supplies_supply_id_trbx_get

        Получить список коробов поставки
        """
        pass

    def test_api_v3_supplies_supply_id_trbx_post(self) -> None:
        """Test case for api_v3_supplies_supply_id_trbx_post

        Добавить короба к поставке
        """
        pass

    def test_api_v3_supplies_supply_id_trbx_stickers_post(self) -> None:
        """Test case for api_v3_supplies_supply_id_trbx_stickers_post

        Получить стикеры коробов поставки
        """
        pass

    def test_api_v3_supplies_supply_id_trbx_trbx_id_orders_order_id_delete(self) -> None:
        """Test case for api_v3_supplies_supply_id_trbx_trbx_id_orders_order_id_delete

        Удалить заказ из короба
        """
        pass

    def test_api_v3_supplies_supply_id_trbx_trbx_id_patch(self) -> None:
        """Test case for api_v3_supplies_supply_id_trbx_trbx_id_patch

        Добавить заказы к коробу
        """
        pass

    def test_api_v3_warehouses_get(self) -> None:
        """Test case for api_v3_warehouses_get

        Получить список складов продавца
        """
        pass

    def test_api_v3_warehouses_post(self) -> None:
        """Test case for api_v3_warehouses_post

        Создать склад продавца
        """
        pass

    def test_api_v3_warehouses_warehouse_id_delete(self) -> None:
        """Test case for api_v3_warehouses_warehouse_id_delete

        Удалить склад продавца
        """
        pass

    def test_api_v3_warehouses_warehouse_id_put(self) -> None:
        """Test case for api_v3_warehouses_warehouse_id_put

        Обновить склад
        """
        pass

    def test_api_v5_supplier_report_detail_by_period_get(self) -> None:
        """Test case for api_v5_supplier_report_detail_by_period_get

        Отчет о продажах по реализации
        """
        pass

    def test_content_v2_barcodes_post(self) -> None:
        """Test case for content_v2_barcodes_post

        Генерация баркодов
        """
        pass

    def test_content_v2_cards_delete_trash_post(self) -> None:
        """Test case for content_v2_cards_delete_trash_post

        Перенос НМ в корзину
        """
        pass

    def test_content_v2_cards_error_list_get(self) -> None:
        """Test case for content_v2_cards_error_list_get

        Список несозданных номенклатур (НМ) с ошибками
        """
        pass

    def test_content_v2_cards_limits_get(self) -> None:
        """Test case for content_v2_cards_limits_get

        Лимиты по КТ
        """
        pass

    def test_content_v2_cards_move_nm_post(self) -> None:
        """Test case for content_v2_cards_move_nm_post

        Объединение / Разъединение НМ
        """
        pass

    def test_content_v2_cards_recover_post(self) -> None:
        """Test case for content_v2_cards_recover_post

        Восстановление НМ из корзины
        """
        pass

    def test_content_v2_cards_update_post(self) -> None:
        """Test case for content_v2_cards_update_post

        Редактирование КТ
        """
        pass

    def test_content_v2_cards_upload_add_post(self) -> None:
        """Test case for content_v2_cards_upload_add_post

        Добавление НМ к КТ
        """
        pass

    def test_content_v2_cards_upload_post(self) -> None:
        """Test case for content_v2_cards_upload_post

        Создание карточки товара
        """
        pass

    def test_content_v2_directory_colors_get(self) -> None:
        """Test case for content_v2_directory_colors_get

        Цвет
        """
        pass

    def test_content_v2_directory_countries_get(self) -> None:
        """Test case for content_v2_directory_countries_get

        Страна Производства
        """
        pass

    def test_content_v2_directory_kinds_get(self) -> None:
        """Test case for content_v2_directory_kinds_get

        Пол
        """
        pass

    def test_content_v2_directory_seasons_get(self) -> None:
        """Test case for content_v2_directory_seasons_get

        Сезон
        """
        pass

    def test_content_v2_directory_tnved_get(self) -> None:
        """Test case for content_v2_directory_tnved_get

        ТНВЭД код
        """
        pass

    def test_content_v2_directory_vat_get(self) -> None:
        """Test case for content_v2_directory_vat_get

        Ставка НДС
        """
        pass

    def test_content_v2_get_cards_list_post(self) -> None:
        """Test case for content_v2_get_cards_list_post

        Список номенклатур (НМ)
        """
        pass

    def test_content_v2_get_cards_trash_post(self) -> None:
        """Test case for content_v2_get_cards_trash_post

        Список НМ, находящихся в корзине
        """
        pass

    def test_content_v2_object_all_get(self) -> None:
        """Test case for content_v2_object_all_get

        Список предметов (подкатегорий)
        """
        pass

    def test_content_v2_object_charcs_subject_id_get(self) -> None:
        """Test case for content_v2_object_charcs_subject_id_get

        Характеристики предмета (подкатегории)
        """
        pass

    def test_content_v2_object_parent_all_get(self) -> None:
        """Test case for content_v2_object_parent_all_get

        Родительские категории товаров
        """
        pass

    def test_content_v2_tag_id_delete(self) -> None:
        """Test case for content_v2_tag_id_delete

        Удаление тега
        """
        pass

    def test_content_v2_tag_id_patch(self) -> None:
        """Test case for content_v2_tag_id_patch

        Изменение тега
        """
        pass

    def test_content_v2_tag_nomenclature_link_post(self) -> None:
        """Test case for content_v2_tag_nomenclature_link_post

        Управление тегами в КТ
        """
        pass

    def test_content_v2_tag_post(self) -> None:
        """Test case for content_v2_tag_post

        Создание тега
        """
        pass

    def test_content_v2_tags_get(self) -> None:
        """Test case for content_v2_tags_get

        Список тегов
        """
        pass

    def test_content_v3_media_file_post(self) -> None:
        """Test case for content_v3_media_file_post

        Добавить медиафайлы
        """
        pass

    def test_content_v3_media_save_post(self) -> None:
        """Test case for content_v3_media_save_post

        Изменить медиафайлы
        """
        pass


if __name__ == '__main__':
    unittest.main()
