# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.message_response import MessageResponse

class TestMessageResponse(unittest.TestCase):
    """MessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageResponse:
        """Test MessageResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageResponse`
        """
        model = MessageResponse()
        if include_optional:
            return MessageResponse(
                errors = [
                    ''
                    ],
                result = wildberries_async_api_client.models.message_response_result.MessageResponse_result(
                    add_time = 56, 
                    chat_id = '', )
            )
        else:
            return MessageResponse(
        )
        """

    def testMessageResponse(self):
        """Test MessageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
