# coding: utf-8

"""
    Описание API Marketplace

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wb_client.models.trbx_stickers import TrbxStickers

class TestTrbxStickers(unittest.TestCase):
    """TrbxStickers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrbxStickers:
        """Test TrbxStickers
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrbxStickers`
        """
        model = TrbxStickers()
        if include_optional:
            return TrbxStickers(
                barcode = '$WBMP:1:123:1234567',
                file = '[B@32232e55'
            )
        else:
            return TrbxStickers(
        )
        """

    def testTrbxStickers(self):
        """Test TrbxStickers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
