# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.nm_report_detail_history_response import NmReportDetailHistoryResponse

class TestNmReportDetailHistoryResponse(unittest.TestCase):
    """NmReportDetailHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NmReportDetailHistoryResponse:
        """Test NmReportDetailHistoryResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NmReportDetailHistoryResponse`
        """
        model = NmReportDetailHistoryResponse()
        if include_optional:
            return NmReportDetailHistoryResponse(
                data = [
                    wildberries_async_api_client.models.nm_report_detail_history_response_data_inner.NmReportDetailHistoryResponse_data_inner(
                        nm_id = 1234567, 
                        imt_name = 'Наименование КТ', 
                        vendor_code = 'supplierVendor', 
                        history = [
                            wildberries_async_api_client.models.nm_report_detail_history_response_data_inner_history_inner.NmReportDetailHistoryResponse_data_inner_history_inner(
                                dt = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                open_card_count = 26, 
                                add_to_cart_count = 1, 
                                orders_count = 0, 
                                orders_sum_rub = 0, 
                                buyouts_count = 0, 
                                buyouts_sum_rub = 0, 
                                buyout_percent = 0, 
                                add_to_cart_conversion = 3.8, 
                                cart_to_order_conversion = 0, )
                            ], )
                    ],
                error = True,
                error_text = '',
                additional_errors = [
                    wildberries_async_api_client.models.response_error_additional_errors_inner.responseError_additionalErrors_inner(
                        field = '', 
                        description = '', )
                    ]
            )
        else:
            return NmReportDetailHistoryResponse(
        )
        """

    def testNmReportDetailHistoryResponse(self):
        """Test NmReportDetailHistoryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
