# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v3_supplies_supply_id_trbx_post201_response import ApiV3SuppliesSupplyIdTrbxPost201Response

class TestApiV3SuppliesSupplyIdTrbxPost201Response(unittest.TestCase):
    """ApiV3SuppliesSupplyIdTrbxPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3SuppliesSupplyIdTrbxPost201Response:
        """Test ApiV3SuppliesSupplyIdTrbxPost201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3SuppliesSupplyIdTrbxPost201Response`
        """
        model = ApiV3SuppliesSupplyIdTrbxPost201Response()
        if include_optional:
            return ApiV3SuppliesSupplyIdTrbxPost201Response(
                trbx_ids = [
                    'WB-TRBX-1234567'
                    ]
            )
        else:
            return ApiV3SuppliesSupplyIdTrbxPost201Response(
        )
        """

    def testApiV3SuppliesSupplyIdTrbxPost201Response(self):
        """Test ApiV3SuppliesSupplyIdTrbxPost201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
