# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v1_questions_get200_response_data_questions_inner_answer import ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer

class TestApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer(unittest.TestCase):
    """ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer:
        """Test ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer`
        """
        model = ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer()
        if include_optional:
            return ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer(
                text = '',
                editable = True,
                create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer(
        )
        """

    def testApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer(self):
        """Test ApiV1QuestionsGet200ResponseDataQuestionsInnerAnswer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
