# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v1_auto_stat_get200_response import AdvV1AutoStatGet200Response

class TestAdvV1AutoStatGet200Response(unittest.TestCase):
    """AdvV1AutoStatGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV1AutoStatGet200Response:
        """Test AdvV1AutoStatGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV1AutoStatGet200Response`
        """
        model = AdvV1AutoStatGet200Response()
        if include_optional:
            return AdvV1AutoStatGet200Response(
                views = 56,
                clicks = 1.337,
                ctr = 1.337,
                cpc = 1.337,
                spend = 56
            )
        else:
            return AdvV1AutoStatGet200Response(
        )
        """

    def testAdvV1AutoStatGet200Response(self):
        """Test AdvV1AutoStatGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
