# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.response_info_advert_type8_auto_params import ResponseInfoAdvertType8AutoParams

class TestResponseInfoAdvertType8AutoParams(unittest.TestCase):
    """ResponseInfoAdvertType8AutoParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseInfoAdvertType8AutoParams:
        """Test ResponseInfoAdvertType8AutoParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseInfoAdvertType8AutoParams`
        """
        model = ResponseInfoAdvertType8AutoParams()
        if include_optional:
            return ResponseInfoAdvertType8AutoParams(
                subject = wildberries_async_api_client.models.response_info_advert_type8_auto_params_subject.ResponseInfoAdvertType8_autoParams_subject(
                    id = 56, 
                    name = '', ),
                sets = [
                    wildberries_async_api_client.models.response_info_advert_type8_auto_params_sets_inner.ResponseInfoAdvertType8_autoParams_sets_inner(
                        id = 56, 
                        name = '', )
                    ],
                menus = [
                    wildberries_async_api_client.models.response_info_advert_type8_auto_params_menus_inner.ResponseInfoAdvertType8_autoParams_menus_inner(
                        id = 56, 
                        name = '', )
                    ],
                active = wildberries_async_api_client.models.response_info_advert_type8_auto_params_active.ResponseInfoAdvertType8_autoParams_active(
                    carousel = True, 
                    recom = True, 
                    booster = True, ),
                nm_cpm = [
                    wildberries_async_api_client.models.response_info_advert_type8_auto_params_nm_cpm_inner.ResponseInfoAdvertType8_autoParams_nmCPM_inner(
                        nm = 56, 
                        cpm = 56, )
                    ],
                nms = [
                    56
                    ],
                cpm = 56
            )
        else:
            return ResponseInfoAdvertType8AutoParams(
        )
        """

    def testResponseInfoAdvertType8AutoParams(self):
        """Test ResponseInfoAdvertType8AutoParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
