# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v1_supplier_valuations_get200_response import ApiV1SupplierValuationsGet200Response

class TestApiV1SupplierValuationsGet200Response(unittest.TestCase):
    """ApiV1SupplierValuationsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1SupplierValuationsGet200Response:
        """Test ApiV1SupplierValuationsGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1SupplierValuationsGet200Response`
        """
        model = ApiV1SupplierValuationsGet200Response()
        if include_optional:
            return ApiV1SupplierValuationsGet200Response(
                data = wildberries_async_api_client.models._api_v1_supplier_valuations_get_200_response_data._api_v1_supplier_valuations_get_200_response_data(
                    feedback_valuations = wildberries_async_api_client.models._api_v1_supplier_valuations_get_200_response_data_feedback_valuations._api_v1_supplier_valuations_get_200_response_data_feedbackValuations(
                        1 = '', 
                        2 = '', 
                        3 = '', 
                        4 = '', 
                        5 = '', 
                        6 = '', 
                        7 = '', ), 
                    product_valuations = wildberries_async_api_client.models._api_v1_supplier_valuations_get_200_response_data_product_valuations._api_v1_supplier_valuations_get_200_response_data_productValuations(
                        1 = '', 
                        2 = '', 
                        3 = '', 
                        4 = '', ), ),
                error = True,
                error_text = '',
                additional_errors = [
                    ''
                    ]
            )
        else:
            return ApiV1SupplierValuationsGet200Response(
        )
        """

    def testApiV1SupplierValuationsGet200Response(self):
        """Test ApiV1SupplierValuationsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
