# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.stats1_inner import Stats1Inner

class TestStats1Inner(unittest.TestCase):
    """Stats1Inner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Stats1Inner:
        """Test Stats1Inner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Stats1Inner`
        """
        model = Stats1Inner()
        if include_optional:
            return Stats1Inner(
                views = 56,
                clicks = 56,
                atbs = 56,
                ctr = 1.337
            )
        else:
            return Stats1Inner(
        )
        """

    def testStats1Inner(self):
        """Test Stats1Inner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
