# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_get_cards_list_post200_response_cards_inner_photos_inner import ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner

class TestContentV2GetCardsListPost200ResponseCardsInnerPhotosInner(unittest.TestCase):
    """ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner:
        """Test ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner`
        """
        model = ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner()
        if include_optional:
            return ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner(
                big = '',
                c246x328 = '',
                c516x688 = '',
                square = '',
                tm = ''
            )
        else:
            return ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner(
        )
        """

    def testContentV2GetCardsListPost200ResponseCardsInnerPhotosInner(self):
        """Test ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
