# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.response_info_advert_type8_auto_params_menus_inner import ResponseInfoAdvertType8AutoParamsMenusInner

class TestResponseInfoAdvertType8AutoParamsMenusInner(unittest.TestCase):
    """ResponseInfoAdvertType8AutoParamsMenusInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseInfoAdvertType8AutoParamsMenusInner:
        """Test ResponseInfoAdvertType8AutoParamsMenusInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseInfoAdvertType8AutoParamsMenusInner`
        """
        model = ResponseInfoAdvertType8AutoParamsMenusInner()
        if include_optional:
            return ResponseInfoAdvertType8AutoParamsMenusInner(
                id = 56,
                name = ''
            )
        else:
            return ResponseInfoAdvertType8AutoParamsMenusInner(
        )
        """

    def testResponseInfoAdvertType8AutoParamsMenusInner(self):
        """Test ResponseInfoAdvertType8AutoParamsMenusInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
