# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.nm_report_retry_report_request import NmReportRetryReportRequest

class TestNmReportRetryReportRequest(unittest.TestCase):
    """NmReportRetryReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NmReportRetryReportRequest:
        """Test NmReportRetryReportRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NmReportRetryReportRequest`
        """
        model = NmReportRetryReportRequest()
        if include_optional:
            return NmReportRetryReportRequest(
                download_id = '06eea887-9d9f-491f-b16a-bb1766fcb8d2'
            )
        else:
            return NmReportRetryReportRequest(
        )
        """

    def testNmReportRetryReportRequest(self):
        """Test NmReportRetryReportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
