# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v1_promotion_adverts_post200_response import AdvV1PromotionAdvertsPost200Response

class TestAdvV1PromotionAdvertsPost200Response(unittest.TestCase):
    """AdvV1PromotionAdvertsPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV1PromotionAdvertsPost200Response:
        """Test AdvV1PromotionAdvertsPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV1PromotionAdvertsPost200Response`
        """
        model = AdvV1PromotionAdvertsPost200Response()
        if include_optional:
            return AdvV1PromotionAdvertsPost200Response(
                advert_id = 56,
                type = 56,
                status = 56,
                daily_budget = 56,
                create_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                change_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                params = [
                    wildberries_async_api_client.models.response_info_advert_params_inner.ResponseInfoAdvert_params_inner(
                        subject_name = '', 
                        active = True, 
                        intervals = [
                            wildberries_async_api_client.models.response_info_advert_params_inner_intervals_inner.ResponseInfoAdvert_params_inner_intervals_inner(
                                begin = 56, 
                                end = 56, )
                            ], 
                        price = 56, 
                        menu_id = 56, 
                        subject_id = 56, 
                        set_id = 56, 
                        set_name = '', 
                        menu_name = '', 
                        nms = [
                            wildberries_async_api_client.models.response_info_advert_params_inner_nms_inner.ResponseInfoAdvert_params_inner_nms_inner(
                                nm = 56, 
                                active = True, )
                            ], )
                    ],
                search_pluse_state = True,
                auto_params = wildberries_async_api_client.models.response_info_advert_type8_auto_params.ResponseInfoAdvertType8_autoParams(
                    subject = wildberries_async_api_client.models.response_info_advert_type8_auto_params_subject.ResponseInfoAdvertType8_autoParams_subject(
                        id = 56, 
                        name = '', ), 
                    sets = [
                        wildberries_async_api_client.models.response_info_advert_type8_auto_params_sets_inner.ResponseInfoAdvertType8_autoParams_sets_inner(
                            id = 56, 
                            name = '', )
                        ], 
                    menus = [
                        wildberries_async_api_client.models.response_info_advert_type8_auto_params_menus_inner.ResponseInfoAdvertType8_autoParams_menus_inner(
                            id = 56, 
                            name = '', )
                        ], 
                    active = wildberries_async_api_client.models.response_info_advert_type8_auto_params_active.ResponseInfoAdvertType8_autoParams_active(
                        carousel = True, 
                        recom = True, 
                        booster = True, ), 
                    nm_cpm = [
                        wildberries_async_api_client.models.response_info_advert_type8_auto_params_nm_cpm_inner.ResponseInfoAdvertType8_autoParams_nmCPM_inner(
                            nm = 56, 
                            cpm = 56, )
                        ], 
                    nms = [
                        56
                        ], 
                    cpm = 56, ),
                united_params = [
                    wildberries_async_api_client.models.response_info_advert_type9_united_params_inner.ResponseInfoAdvertType9_unitedParams_inner(
                        subject = wildberries_async_api_client.models.response_info_advert_type9_united_params_inner_subject.ResponseInfoAdvertType9_unitedParams_inner_subject(
                            id = 56, 
                            name = '', ), 
                        menus = [
                            wildberries_async_api_client.models.response_info_advert_type9_united_params_inner_menus_inner.ResponseInfoAdvertType9_unitedParams_inner_menus_inner(
                                id = 56, 
                                name = '', )
                            ], 
                        nms = [
                            56
                            ], 
                        search_cpm = 56, 
                        catalog_cpm = 56, )
                    ]
            )
        else:
            return AdvV1PromotionAdvertsPost200Response(
        )
        """

    def testAdvV1PromotionAdvertsPost200Response(self):
        """Test AdvV1PromotionAdvertsPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
