# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.return_tariffs_response import ReturnTariffsResponse

class TestReturnTariffsResponse(unittest.TestCase):
    """ReturnTariffsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReturnTariffsResponse:
        """Test ReturnTariffsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReturnTariffsResponse`
        """
        model = ReturnTariffsResponse()
        if include_optional:
            return ReturnTariffsResponse(
                response = wildberries_async_api_client.models.models/return_tariffs_response.models.ReturnTariffsResponse(
                    data = wildberries_async_api_client.models.models/warehouses_return_rates.models.WarehousesReturnRates(
                        dt_next_delivery_dump_kgt = '{}', 
                        dt_next_delivery_dump_srg = '{}', 
                        dt_next_delivery_dump_sup = '{}', 
                        warehouse_list = [
                            wildberries_async_api_client.models.models/warehouse_return_rates.models.WarehouseReturnRates(
                                delivery_dump_kgt_office_base = '100', 
                                delivery_dump_kgt_office_liter = '30', 
                                delivery_dump_kgt_return_expr = '200', 
                                delivery_dump_srg_office_expr = '200', 
                                delivery_dump_srg_return_expr = '200', 
                                delivery_dump_sup_courier_base = '', 
                                delivery_dump_sup_courier_liter = '', 
                                delivery_dump_sup_office_base = '200', 
                                delivery_dump_sup_office_liter = '50', 
                                delivery_dump_sup_return_expr = '200', 
                                warehouse_name = 'Коледино', )
                            ], ), )
            )
        else:
            return ReturnTariffsResponse(
        )
        """

    def testReturnTariffsResponse(self):
        """Test ReturnTariffsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
