# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v1_advert_pause_post_request import AdvV1AdvertPausePostRequest

class TestAdvV1AdvertPausePostRequest(unittest.TestCase):
    """AdvV1AdvertPausePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV1AdvertPausePostRequest:
        """Test AdvV1AdvertPausePostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV1AdvertPausePostRequest`
        """
        model = AdvV1AdvertPausePostRequest()
        if include_optional:
            return AdvV1AdvertPausePostRequest(
                advert_id = 56,
                reason = ''
            )
        else:
            return AdvV1AdvertPausePostRequest(
                advert_id = 56,
        )
        """

    def testAdvV1AdvertPausePostRequest(self):
        """Test AdvV1AdvertPausePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
