# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_get_cards_list_post_request import ContentV2GetCardsListPostRequest

class TestContentV2GetCardsListPostRequest(unittest.TestCase):
    """ContentV2GetCardsListPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2GetCardsListPostRequest:
        """Test ContentV2GetCardsListPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2GetCardsListPostRequest`
        """
        model = ContentV2GetCardsListPostRequest()
        if include_optional:
            return ContentV2GetCardsListPostRequest(
                settings = wildberries_async_api_client.models._content_v2_get_cards_list_post_request_settings._content_v2_get_cards_list_post_request_settings(
                    sort = wildberries_async_api_client.models._content_v2_get_cards_list_post_request_settings_sort._content_v2_get_cards_list_post_request_settings_sort(
                        ascending = True, ), 
                    filter = wildberries_async_api_client.models._content_v2_get_cards_list_post_request_settings_filter._content_v2_get_cards_list_post_request_settings_filter(
                        with_photo = 56, 
                        text_search = '', 
                        tag_ids = [
                            56
                            ], 
                        allowed_categories_only = True, 
                        object_ids = [
                            56
                            ], 
                        brands = [
                            ''
                            ], 
                        imt_id = 56, ), 
                    cursor = wildberries_async_api_client.models._content_v2_get_cards_list_post_request_settings_cursor._content_v2_get_cards_list_post_request_settings_cursor(
                        limit = 56, ), )
            )
        else:
            return ContentV2GetCardsListPostRequest(
        )
        """

    def testContentV2GetCardsListPostRequest(self):
        """Test ContentV2GetCardsListPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
