# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.commission_turkey_report_inner import CommissionTurkeyReportInner

class TestCommissionTurkeyReportInner(unittest.TestCase):
    """CommissionTurkeyReportInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommissionTurkeyReportInner:
        """Test CommissionTurkeyReportInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommissionTurkeyReportInner`
        """
        model = CommissionTurkeyReportInner()
        if include_optional:
            return CommissionTurkeyReportInner(
                kgvp_turkey = 1.337,
                parent_id = 56,
                parent_name = '',
                subject_id = 56,
                subject_name = ''
            )
        else:
            return CommissionTurkeyReportInner(
        )
        """

    def testCommissionTurkeyReportInner(self):
        """Test CommissionTurkeyReportInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
