# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.nm_report_grouped_response_data_groups_inner_statistics_previous_period_conversions import NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions

class TestNmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions(unittest.TestCase):
    """NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions:
        """Test NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions`
        """
        model = NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions()
        if include_optional:
            return NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions(
                add_to_cart_percent = 15.5,
                cart_to_order_percent = 116.7,
                buyouts_percent = 84.1
            )
        else:
            return NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions(
        )
        """

    def testNmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions(self):
        """Test NmReportGroupedResponseDataGroupsInnerStatisticsPreviousPeriodConversions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
