# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.nm_report_detail_request_period import NmReportDetailRequestPeriod

class TestNmReportDetailRequestPeriod(unittest.TestCase):
    """NmReportDetailRequestPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NmReportDetailRequestPeriod:
        """Test NmReportDetailRequestPeriod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NmReportDetailRequestPeriod`
        """
        model = NmReportDetailRequestPeriod()
        if include_optional:
            return NmReportDetailRequestPeriod(
                begin = '{}',
                end = '{}'
            )
        else:
            return NmReportDetailRequestPeriod(
        )
        """

    def testNmReportDetailRequestPeriod(self):
        """Test NmReportDetailRequestPeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
