# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.response_advert401 import ResponseAdvert401

class TestResponseAdvert401(unittest.TestCase):
    """ResponseAdvert401 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseAdvert401:
        """Test ResponseAdvert401
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseAdvert401`
        """
        model = ResponseAdvert401()
        if include_optional:
            return ResponseAdvert401(
                code = 56,
                message = '',
                rejected = ''
            )
        else:
            return ResponseAdvert401(
        )
        """

    def testResponseAdvert401(self):
        """Test ResponseAdvert401"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
