# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v0_params_menu_get200_response_inner import AdvV0ParamsMenuGet200ResponseInner

class TestAdvV0ParamsMenuGet200ResponseInner(unittest.TestCase):
    """AdvV0ParamsMenuGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV0ParamsMenuGet200ResponseInner:
        """Test AdvV0ParamsMenuGet200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV0ParamsMenuGet200ResponseInner`
        """
        model = AdvV0ParamsMenuGet200ResponseInner()
        if include_optional:
            return AdvV0ParamsMenuGet200ResponseInner(
                id = 56,
                name = ''
            )
        else:
            return AdvV0ParamsMenuGet200ResponseInner(
        )
        """

    def testAdvV0ParamsMenuGet200ResponseInner(self):
        """Test AdvV0ParamsMenuGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
