# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_cards_delete_trash_post_request_inner import ContentV2CardsDeleteTrashPostRequestInner

class TestContentV2CardsDeleteTrashPostRequestInner(unittest.TestCase):
    """ContentV2CardsDeleteTrashPostRequestInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2CardsDeleteTrashPostRequestInner:
        """Test ContentV2CardsDeleteTrashPostRequestInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2CardsDeleteTrashPostRequestInner`
        """
        model = ContentV2CardsDeleteTrashPostRequestInner()
        if include_optional:
            return ContentV2CardsDeleteTrashPostRequestInner(
                nm_ids = [
                    56
                    ]
            )
        else:
            return ContentV2CardsDeleteTrashPostRequestInner(
        )
        """

    def testContentV2CardsDeleteTrashPostRequestInner(self):
        """Test ContentV2CardsDeleteTrashPostRequestInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
