# coding: utf-8

"""
    Описание API Marketplace

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wb_client.models.office import Office

class TestOffice(unittest.TestCase):
    """Office unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Office:
        """Test Office
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Office`
        """
        model = Office()
        if include_optional:
            return Office(
                address = 'ул. Троицкая, Подольск, Московская обл.',
                name = 'Москва (Коледино)',
                city = 'Москва',
                id = 15,
                longitude = 55.386871,
                latitude = 37.588898,
                cargo_type = 1,
                delivery_type = 1,
                selected = True
            )
        else:
            return Office(
        )
        """

    def testOffice(self):
        """Test Office"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
