# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v1_feedbacks_products_rating_get200_response_data import ApiV1FeedbacksProductsRatingGet200ResponseData

class TestApiV1FeedbacksProductsRatingGet200ResponseData(unittest.TestCase):
    """ApiV1FeedbacksProductsRatingGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1FeedbacksProductsRatingGet200ResponseData:
        """Test ApiV1FeedbacksProductsRatingGet200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1FeedbacksProductsRatingGet200ResponseData`
        """
        model = ApiV1FeedbacksProductsRatingGet200ResponseData()
        if include_optional:
            return ApiV1FeedbacksProductsRatingGet200ResponseData(
                valuation = '4.8',
                feedbacks_count = 277
            )
        else:
            return ApiV1FeedbacksProductsRatingGet200ResponseData(
        )
        """

    def testApiV1FeedbacksProductsRatingGet200ResponseData(self):
        """Test ApiV1FeedbacksProductsRatingGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
