# coding: utf-8

"""
    Описание API Marketplace

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wb_client.models.api_v3_stocks_warehouse_id_put_request_stocks_inner import ApiV3StocksWarehouseIdPutRequestStocksInner

class TestApiV3StocksWarehouseIdPutRequestStocksInner(unittest.TestCase):
    """ApiV3StocksWarehouseIdPutRequestStocksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV3StocksWarehouseIdPutRequestStocksInner:
        """Test ApiV3StocksWarehouseIdPutRequestStocksInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV3StocksWarehouseIdPutRequestStocksInner`
        """
        model = ApiV3StocksWarehouseIdPutRequestStocksInner()
        if include_optional:
            return ApiV3StocksWarehouseIdPutRequestStocksInner(
                sku = 'BarcodeTest123',
                amount = 10
            )
        else:
            return ApiV3StocksWarehouseIdPutRequestStocksInner(
        )
        """

    def testApiV3StocksWarehouseIdPutRequestStocksInner(self):
        """Test ApiV3StocksWarehouseIdPutRequestStocksInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
