# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_cards_error_list_get200_response_data_inner import ContentV2CardsErrorListGet200ResponseDataInner

class TestContentV2CardsErrorListGet200ResponseDataInner(unittest.TestCase):
    """ContentV2CardsErrorListGet200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2CardsErrorListGet200ResponseDataInner:
        """Test ContentV2CardsErrorListGet200ResponseDataInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2CardsErrorListGet200ResponseDataInner`
        """
        model = ContentV2CardsErrorListGet200ResponseDataInner()
        if include_optional:
            return ContentV2CardsErrorListGet200ResponseDataInner(
                object = 'Блузки',
                vendor_code = '6000000001',
                update_at = '2022-06-15T14:37:13Z',
                errors = [
                    'Поля Рос. размер, Размер обязательны для заполнения'
                    ],
                object_id = 41
            )
        else:
            return ContentV2CardsErrorListGet200ResponseDataInner(
        )
        """

    def testContentV2CardsErrorListGet200ResponseDataInner(self):
        """Test ContentV2CardsErrorListGet200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
