# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_cards_upload_add_post_request import ContentV2CardsUploadAddPostRequest

class TestContentV2CardsUploadAddPostRequest(unittest.TestCase):
    """ContentV2CardsUploadAddPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2CardsUploadAddPostRequest:
        """Test ContentV2CardsUploadAddPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2CardsUploadAddPostRequest`
        """
        model = ContentV2CardsUploadAddPostRequest()
        if include_optional:
            return ContentV2CardsUploadAddPostRequest(
                imt_id = 56,
                cards_to_add = [
                    wildberries_async_api_client.models._content_v2_cards_upload_add_post_request_cards_to_add_inner._content_v2_cards_upload_add_post_request_cardsToAdd_inner(
                        brand = '', 
                        vendor_code = '', 
                        title = '', 
                        description = '', 
                        dimensions = wildberries_async_api_client.models._content_v2_cards_upload_post_request_inner_variants_inner_dimensions._content_v2_cards_upload_post_request_inner_variants_inner_dimensions(
                            length = 56, 
                            width = 56, 
                            height = 56, ), 
                        characteristics = [
                            wildberries_async_api_client.models._content_v2_cards_upload_add_post_request_cards_to_add_inner_characteristics_inner._content_v2_cards_upload_add_post_request_cardsToAdd_inner_characteristics_inner(
                                id = 56, 
                                value = null, )
                            ], 
                        sizes = [
                            wildberries_async_api_client.models._content_v2_cards_upload_add_post_request_cards_to_add_inner_sizes_inner._content_v2_cards_upload_add_post_request_cardsToAdd_inner_sizes_inner(
                                tech_size = '', 
                                wb_size = '', 
                                price = 56, 
                                skus = [
                                    ''
                                    ], )
                            ], )
                    ]
            )
        else:
            return ContentV2CardsUploadAddPostRequest(
        )
        """

    def testContentV2CardsUploadAddPostRequest(self):
        """Test ContentV2CardsUploadAddPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
