# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v2_history_tasks_get200_response import ApiV2HistoryTasksGet200Response

class TestApiV2HistoryTasksGet200Response(unittest.TestCase):
    """ApiV2HistoryTasksGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV2HistoryTasksGet200Response:
        """Test ApiV2HistoryTasksGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV2HistoryTasksGet200Response`
        """
        model = ApiV2HistoryTasksGet200Response()
        if include_optional:
            return ApiV2HistoryTasksGet200Response(
                data = wildberries_async_api_client.models.supplier_task_metadata.SupplierTaskMetadata(
                    upload_id = 395643565, 
                    status = 3, 
                    upload_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    activation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    over_all_goods_number = 56, 
                    success_goods_number = 56, ),
                error = False,
                error_text = 'The product is in quarantine'
            )
        else:
            return ApiV2HistoryTasksGet200Response(
        )
        """

    def testApiV2HistoryTasksGet200Response(self):
        """Test ApiV2HistoryTasksGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
