# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.content_v2_object_charcs_subject_id_get200_response import ContentV2ObjectCharcsSubjectIdGet200Response

class TestContentV2ObjectCharcsSubjectIdGet200Response(unittest.TestCase):
    """ContentV2ObjectCharcsSubjectIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV2ObjectCharcsSubjectIdGet200Response:
        """Test ContentV2ObjectCharcsSubjectIdGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV2ObjectCharcsSubjectIdGet200Response`
        """
        model = ContentV2ObjectCharcsSubjectIdGet200Response()
        if include_optional:
            return ContentV2ObjectCharcsSubjectIdGet200Response(
                data = [
                    wildberries_async_api_client.models._content_v2_object_charcs__subject_id__get_200_response_data_inner._content_v2_object_charcs__subjectId__get_200_response_data_inner(
                        charc_id = 56, 
                        subject_name = '', 
                        subject_id = 56, 
                        name = '', 
                        required = True, 
                        unit_name = '', 
                        max_count = 56, 
                        popular = True, 
                        charc_type = 56, )
                    ],
                error = True,
                error_text = '',
                additional_errors = ''
            )
        else:
            return ContentV2ObjectCharcsSubjectIdGet200Response(
        )
        """

    def testContentV2ObjectCharcsSubjectIdGet200Response(self):
        """Test ContentV2ObjectCharcsSubjectIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
