# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.supply_trbx import SupplyTrbx

class TestSupplyTrbx(unittest.TestCase):
    """SupplyTrbx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupplyTrbx:
        """Test SupplyTrbx
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupplyTrbx`
        """
        model = SupplyTrbx()
        if include_optional:
            return SupplyTrbx(
                id = 'WB-TRBX-1234567',
                orders = [
                    1234567
                    ]
            )
        else:
            return SupplyTrbx(
        )
        """

    def testSupplyTrbx(self):
        """Test SupplyTrbx"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
