# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v0_cpm_post_request import AdvV0CpmPostRequest

class TestAdvV0CpmPostRequest(unittest.TestCase):
    """AdvV0CpmPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV0CpmPostRequest:
        """Test AdvV0CpmPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV0CpmPostRequest`
        """
        model = AdvV0CpmPostRequest()
        if include_optional:
            return AdvV0CpmPostRequest(
                advert_id = 789,
                type = 5,
                cpm = 456,
                param = 23,
                instrument = 4
            )
        else:
            return AdvV0CpmPostRequest(
                advert_id = 789,
                type = 5,
                cpm = 456,
                param = 23,
        )
        """

    def testAdvV0CpmPostRequest(self):
        """Test AdvV0CpmPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
