# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v1_analytics_incorrect_attachments_get200_response_report_inner import ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner

class TestApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner(unittest.TestCase):
    """ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner:
        """Test ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner`
        """
        model = ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner()
        if include_optional:
            return ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner(
                amount = 24514.5,
                var_date = '{}',
                lost_reason = 'Подмена. Вместо большой железной дороги поступила маленькая коробка.',
                nm_id = 123456789,
                photo_url = 'https://mstatic.wbstatic.net/writeoff_to_the_seller/12345678911-2023-06-21T12:13:37.768Z-1.png',
                shk_id = 14555724540
            )
        else:
            return ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner(
        )
        """

    def testApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner(self):
        """Test ApiV1AnalyticsIncorrectAttachmentsGet200ResponseReportInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
