# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v1_analytics_characteristics_change_get400_response import ApiV1AnalyticsCharacteristicsChangeGet400Response

class TestApiV1AnalyticsCharacteristicsChangeGet400Response(unittest.TestCase):
    """ApiV1AnalyticsCharacteristicsChangeGet400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1AnalyticsCharacteristicsChangeGet400Response:
        """Test ApiV1AnalyticsCharacteristicsChangeGet400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1AnalyticsCharacteristicsChangeGet400Response`
        """
        model = ApiV1AnalyticsCharacteristicsChangeGet400Response()
        if include_optional:
            return ApiV1AnalyticsCharacteristicsChangeGet400Response(
                title = '',
                detail = '',
                request_id = '',
                origin = ''
            )
        else:
            return ApiV1AnalyticsCharacteristicsChangeGet400Response(
        )
        """

    def testApiV1AnalyticsCharacteristicsChangeGet400Response(self):
        """Test ApiV1AnalyticsCharacteristicsChangeGet400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
