# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.adv_v1_supplier_subjects_get200_response_inner import AdvV1SupplierSubjectsGet200ResponseInner

class TestAdvV1SupplierSubjectsGet200ResponseInner(unittest.TestCase):
    """AdvV1SupplierSubjectsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvV1SupplierSubjectsGet200ResponseInner:
        """Test AdvV1SupplierSubjectsGet200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvV1SupplierSubjectsGet200ResponseInner`
        """
        model = AdvV1SupplierSubjectsGet200ResponseInner()
        if include_optional:
            return AdvV1SupplierSubjectsGet200ResponseInner(
                id = 56,
                name = '',
                count = 56
            )
        else:
            return AdvV1SupplierSubjectsGet200ResponseInner(
        )
        """

    def testAdvV1SupplierSubjectsGet200ResponseInner(self):
        """Test AdvV1SupplierSubjectsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
