# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.api_v1_templates_post_request import ApiV1TemplatesPostRequest

class TestApiV1TemplatesPostRequest(unittest.TestCase):
    """ApiV1TemplatesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1TemplatesPostRequest:
        """Test ApiV1TemplatesPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1TemplatesPostRequest`
        """
        model = ApiV1TemplatesPostRequest()
        if include_optional:
            return ApiV1TemplatesPostRequest(
                name = '',
                template_type = 56,
                text = ''
            )
        else:
            return ApiV1TemplatesPostRequest(
                name = '',
                template_type = 56,
                text = '',
        )
        """

    def testApiV1TemplatesPostRequest(self):
        """Test ApiV1TemplatesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
