# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wildberries_async_api_client.models.response_error_statistics import ResponseErrorStatistics

class TestResponseErrorStatistics(unittest.TestCase):
    """ResponseErrorStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseErrorStatistics:
        """Test ResponseErrorStatistics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseErrorStatistics`
        """
        model = ResponseErrorStatistics()
        if include_optional:
            return ResponseErrorStatistics(
                errors = [
                    ''
                    ]
            )
        else:
            return ResponseErrorStatistics(
        )
        """

    def testResponseErrorStatistics(self):
        """Test ResponseErrorStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
