# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from wildberries_async_api_client.models.adv_v1_stat_words_get200_response_stat_inner import AdvV1StatWordsGet200ResponseStatInner
from wildberries_async_api_client.models.adv_v1_stat_words_get200_response_words import AdvV1StatWordsGet200ResponseWords
from typing import Optional, Set
from typing_extensions import Self

class AdvV1StatWordsGet200Response(BaseModel):
    """
    AdvV1StatWordsGet200Response
    """ # noqa: E501
    words: Optional[AdvV1StatWordsGet200ResponseWords] = None
    stat: Optional[List[AdvV1StatWordsGet200ResponseStatInner]] = Field(default=None, description="Массив информации по статистике.<br> <b>Первый элемент массива</b> с `keyword: \"Всего по кампании\"` содержит суммарную информацию по всем ключевым фразам.<br> <b>Каждый следующий элемент массива</b> содержит информацию по отдельной ключевой фразе.<br> Отображается 60 ключевых фраз с наибольшим количеством просмотров. ")
    __properties: ClassVar[List[str]] = ["words", "stat"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdvV1StatWordsGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of words
        if self.words:
            _dict['words'] = self.words.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in stat (list)
        _items = []
        if self.stat:
            for _item in self.stat:
                if _item:
                    _items.append(_item.to_dict())
            _dict['stat'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdvV1StatWordsGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "words": AdvV1StatWordsGet200ResponseWords.from_dict(obj["words"]) if obj.get("words") is not None else None,
            "stat": [AdvV1StatWordsGet200ResponseStatInner.from_dict(_item) for _item in obj["stat"]] if obj.get("stat") is not None else None
        })
        return _obj


