# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from wildberries_async_api_client.models.adv_v1_seacat_stat_get200_response_dates_inner import AdvV1SeacatStatGet200ResponseDatesInner
from typing import Optional, Set
from typing_extensions import Self

class AdvV1SeacatStatGet200Response(BaseModel):
    """
    AdvV1SeacatStatGet200Response
    """ # noqa: E501
    total_views: Optional[StrictInt] = Field(default=None, description="Суммарное количество просмотров", alias="totalViews")
    total_clicks: Optional[StrictInt] = Field(default=None, description="Суммарное количество кликов", alias="totalClicks")
    total_orders: Optional[StrictInt] = Field(default=None, description="Суммарное количество заказов", alias="totalOrders")
    total_sum: Optional[StrictInt] = Field(default=None, description="Суммарные затраты, ₽.", alias="totalSum")
    dates: Optional[List[AdvV1SeacatStatGet200ResponseDatesInner]] = Field(default=None, description="Блок статистики")
    __properties: ClassVar[List[str]] = ["totalViews", "totalClicks", "totalOrders", "totalSum", "dates"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdvV1SeacatStatGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dates (list)
        _items = []
        if self.dates:
            for _item in self.dates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['dates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdvV1SeacatStatGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "totalViews": obj.get("totalViews"),
            "totalClicks": obj.get("totalClicks"),
            "totalOrders": obj.get("totalOrders"),
            "totalSum": obj.get("totalSum"),
            "dates": [AdvV1SeacatStatGet200ResponseDatesInner.from_dict(_item) for _item in obj["dates"]] if obj.get("dates") is not None else None
        })
        return _obj


