# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Office(BaseModel):
    """
    Данные о складе WB
    """ # noqa: E501
    address: Optional[StrictStr] = Field(default=None, description="Адрес")
    name: Optional[StrictStr] = Field(default=None, description="Название")
    city: Optional[StrictStr] = Field(default=None, description="Город")
    id: Optional[StrictInt] = Field(default=None, description="ID")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Долгота")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Широта")
    cargo_type: Optional[StrictInt] = Field(default=None, description="<dl> <dt>Тип товара, который принимает склад:</dt> <dd>1 - обычный</dd> <dd>2 - СГТ (Сверхгабаритный товар)</dd> <dd>3 - КГТ (Крупногабаритный товар). Не используется на данный момент.</dd> </dl> ", alias="cargoType")
    delivery_type: Optional[StrictInt] = Field(default=None, description="<dl> <dt>Тип доставки, который принимает склад:</dt> <dd>1 - доставка на склад Wildberries</dd> <dd>2 - доставка силами продавца</dd> <dd>3 - доставка курьером WB</dd> </dl> ", alias="deliveryType")
    selected: Optional[StrictBool] = Field(default=None, description="Признак того, что склад уже выбран продавцом")
    __properties: ClassVar[List[str]] = ["address", "name", "city", "id", "longitude", "latitude", "cargoType", "deliveryType", "selected"]

    @field_validator('cargo_type')
    def cargo_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3]):
            raise ValueError("must be one of enum values (1, 2, 3)")
        return value

    @field_validator('delivery_type')
    def delivery_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3]):
            raise ValueError("must be one of enum values (1, 2, 3)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Office from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Office from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "name": obj.get("name"),
            "city": obj.get("city"),
            "id": obj.get("id"),
            "longitude": obj.get("longitude"),
            "latitude": obj.get("latitude"),
            "cargoType": obj.get("cargoType"),
            "deliveryType": obj.get("deliveryType"),
            "selected": obj.get("selected")
        })
        return _obj


