# coding: utf-8

"""
    Wildberries API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class OrderAddress(BaseModel):
    """
    Детализованный адрес покупателя для доставки (если применимо). Некоторые из полей могут прийти пустыми из-за специфики адреса
    """ # noqa: E501
    full_address: Optional[StrictStr] = Field(default=None, description="Адрес доставки.", alias="fullAddress")
    province: Optional[StrictStr] = Field(default=None, description="Область")
    area: Optional[StrictStr] = Field(default=None, description="Район")
    city: Optional[StrictStr] = Field(default=None, description="Город")
    street: Optional[StrictStr] = Field(default=None, description="Улица")
    home: Optional[StrictStr] = Field(default=None, description="Номер дома")
    flat: Optional[StrictStr] = Field(default=None, description="Номер квартиры")
    entrance: Optional[StrictStr] = Field(default=None, description="Подъезд")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Координата долготы")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Координаты широты")
    __properties: ClassVar[List[str]] = ["fullAddress", "province", "area", "city", "street", "home", "flat", "entrance", "longitude", "latitude"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fullAddress": obj.get("fullAddress"),
            "province": obj.get("province"),
            "area": obj.get("area"),
            "city": obj.get("city"),
            "street": obj.get("street"),
            "home": obj.get("home"),
            "flat": obj.get("flat"),
            "entrance": obj.get("entrance"),
            "longitude": obj.get("longitude"),
            "latitude": obj.get("latitude")
        })
        return _obj


