openapi: 3.0.1
info:
    title: Wildberries API
    version: ''
tags:
    $include#products: https://dev.wildberries.ru/yaml/en/02-products.yaml#/tags
    $include#orders_fbs: https://dev.wildberries.ru/yaml/en/03-orders-fbs.yaml#/tags
    $include#promotion: https://dev.wildberries.ru/yaml/en/07-promotion.yaml#/tags
    $include#communications: https://dev.wildberries.ru/yaml/en/08-communications.yaml#/tags
paths:
    $include#products: https://dev.wildberries.ru/yaml/en/02-products.yaml#/paths
    $include#orders_fbs: https://dev.wildberries.ru/yaml/en/03-orders-fbs.yaml#/paths
    $include#promotion: https://dev.wildberries.ru/yaml/en/07-promotion.yaml#/paths
    $include#communications: https://dev.wildberries.ru/yaml/en/08-communications.yaml#/paths
components:
    $include#products: https://dev.wildberries.ru/yaml/en/02-products.yaml#/components
    $include#orders_fbs: https://dev.wildberries.ru/yaml/en/03-orders-fbs.yaml#/components
    $include#promotion: https://dev.wildberries.ru/yaml/en/07-promotion.yaml#/components
    $include#communications: https://dev.wildberries.ru/yaml/en/08-communications.yaml#/components
